// examples/react/App.tsx
import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { OTPInput } from '../../src/adapters/react'; // Direct source import for example

function App() {
  const [otp, setOtp] = useState('');

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif' }}>
      <h1>React OTP Example</h1>
      <p>Enter your 6-digit code:</p>
      
      <OTPInput
        length={6}
        value={otp}
        onChange={setOtp}
        onComplete={(code) => alert(`OTP Complete: ${code}`)}
      />
      
      <div style={{ marginTop: '20px' }}>
        <strong>Current Value:</strong> {otp}
      </div>
      
      <button 
        onClick={() => setOtp('')}
        style={{ marginTop: '10px', padding: '8px 16px' }}
      >
        Clear OTP
      </button>
    </div>
  );
}

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}

// examples/vue/App.vue
<template>
  <div class="example">
    <h1>Vue 3 OTP Example</h1>
    <p>Enter your 4-digit code:</p>

    <OTPInput v-model="otp" :length="4" @complete="onComplete" />

    <div class="status"><strong>Current Value:</strong> {{ otp }}</div>

    <button @click="otp = ''">Reset</button>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { OTPInput } from '../../src/adapters/vue';

const otp = ref('');
const onComplete = (code) => {
  alert(`Vue OTP Complete: ${code}`);
};
</script>

<style scoped>
.example {
  padding: 20px;
  font-family: sans-serif;
}
.status {
  margin-top: 20px;
}
button {
  margin-top: 10px;
  padding: 8px 16px;
}
</style>
